cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.index, name="index")

]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.index, name="index")

]

menu/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='menu'
urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls')),
    path('cart/', include('cart.urls')),

]

cart/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models

class Pizza(models.Model):

    name=models.CharField(max_length=200)
    ingredients= models.CharField(max_length=400)
    price=models.FloatField(default=0)
    vegetarian=models.BooleanField(default=False)

    def __str__(self):
        return self.name
# Create your models here.

cart/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

#from .cart import Cart

#def add_to_cart(request, )

def index(request):
    #eturn HttpResponse('Cart')
    return render(request, 'cart/index.html')

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    #return HttpResponse('Main Page')
    return render(request, 'main/index.html')

menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza
# Create your views here.


def index(request):

    pizzas = Pizza.objects.all().order_by('price')
    context = {
        'pizzas': pizzas
    }
    return render(request, 'menu/index.html', context)

cart/templates/cart/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cart</title>
</head>
<body>
<p>This is my cart</p>

<input type="number" id="myText" value="0">
<button type="button" onclick="myFunction()">Save</button>

    <p id="demo"></p>

<script>

    // Here the value is stored in new variable x
        function myFunction() {
        var x = document.getElementById("myText").value;
        document.getElementById("demo").innerHTML = x;


    }
    </script>


</body>
</html>

main/templates/main/index.html
<!DOCTYPE html> {% load static %}
<html lang="en">


<head>
    <meta charset="UTF-8">

    <title>Pizza Mama</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <img id='logo' src="{% static 'main/images/main_logo.png' %}">
    <div id="but">
    <a href="{% url 'menu:index' %}">Our Menu</a>
        </div>
</body>
</html>

menu/templates/menu/index.html
<!DOCTYPE html> {% load static %}
<html lang="en">


<head>
    <meta charset="UTF-8">

    <title>Our Pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
<a href="{% url 'main:index' %}"><img id='logo' src="{% static 'menu/images/small_logo.png' %}"></a>
    <h1>Our Pizzas</h1>
    <ul>
        {% for pizza in pizzas %}
        <table>
            <tr>
                <td id="one" ><b>{{pizza.name}}</b></td><td id="two">{{pizza.price | floatformat:2}}$</td>
            </tr>
        </table>

            <li id="ing">{{pizza.ingredients}}</li>
            {% if pizza.vegetarian %}

            <li style="background-color:#DD7835;
padding:3px;
width:90px;
font-size:13px;
text-align:center;
border-radius:10px;
font-weight:bold;
" >VEGETARIAN</li>

            {% endif %}


        {% endfor %}

    </ul>



</body>
</html>